name = "shopflare-worker"
main = "worker/index.ts"
compatibility_date = "2026-05-31"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "shopflare-db0"
database_id = "f7a387f1-813a-4b85-9554-119fc61cae6c"
migrations_dir = "worker/db/migrations"

[[kv_namespaces]]
binding = "KV"
id = "e0364e783aaf43059dfbb77aaa2fcc0a"

[[r2_buckets]]
bucket_name = "shopflare-images0"
binding = "R2"

[vars]
ENVIRONMENT = "production"
